version: "3.1"

services:

  server:
    build: server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: .env
        target: /var/app/.env
        read_only: true

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db/

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
  #     ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_BASICAUTH_USER}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_BASICAUTH_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:${MONGODB_PORT}/

volumes:
  mongo_data:
